# Site
repository: allanmarum/allanmarum.github.io
# favicon: images/favicon.ico

# Personal info
name: Allan Marconato Marum
title: Control and Automation Engineer
email: allan.marum@gmail.com
website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username:  allanmarum
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: allanmarum
linkedin_username: allanmarum
# pinterest_username: jekyll
youtube_username: allanmarum
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Allan and I'm a control and automation engineer. As well as automation engineer I also have experience developing softwares ans supporting IT/OT applications. I have worked at a number of companies, from small to multinationals, gaining teamwork and flexibility skills.

  I am most skilled in: <mark>PLC Programming</mark> and <mark>Automation Application Support</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in automation and softwares some of my other interests and hobbies are:
   - History
   - Gaming
   - [Be a Youtuber](https://www.youtube.com/user/allanmarum)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
